export const TEXT = {
  App: {
    name: 'Venty',
  },
  Budget: {
    title: 'Budget Dashboard',
    monthHeader: 'BUDGET DASHBOARD',
    startDate: 'START DATE',
    endDate: 'END DATE',
    cashFlowSummary: 'CASH FLOW SUMMARY',
    incomeSummary: 'INCOME SUMMARY',
    billTracker: 'BILL TRACKER',
    expenseSummary: 'EXPENSE SUMMARY',
    savingsTracker: 'SAVINGS TRACKER',
    debtTracker: 'DEBT TRACKER',
    addItem: 'ADD ITEM',
    total: 'TOTAL',
    left: 'LEFT',
    income: 'Income',
    bills: 'Bills',
    expenses: 'Expenses',
    savings: 'Savings',
    debt: 'Debt',
    rollover: 'Rollover',
    noBills: 'No bills added.',
    noSavings: 'No savings goals.',
    newBill: 'New Bill',
    newCategory: 'New Category',
    newGoal: 'New Goal',
    newDebt: 'New Debt',
    categories: [
      'Rent',
      'Food',
      'Transportation',
      'Utilities',
      'Entertainment',
      'Healthcare',
      'Education',
      'Subscriptions',
      'Other',
    ],
  },
  Onboarding: {
    qMonthlyIncome: 'What is your monthly income?',
    qFamilyMembers: 'How many family members do you support?',
    qFixedExpenses: 'What are your fixed monthly expenses?',
  },
  Dashboard: {
    analytics: 'Analytics Dashboard',
    impressions: 'Impressions',
    clicks: 'Clicks',
    ctr: 'CTR',
    conversions: 'Conversions',
  },
  Merchant: {
    marketingCenter: 'Marketing Center',
    adCampaigns: 'Ad Campaigns',
    createNewAd: 'Create New Ad',
    revenue: 'Revenue',
    transactions: 'Transactions',
    payouts: 'Payouts',
    customers: 'Customers',
    performance: 'Performance',
    growBusiness: 'Grow Your Business',
  },
};
